global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'smk-darussalam-subah'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'smk-api'
    scrape_interval: 15s
    static_configs:
      - targets: ['api:3001']
    metrics_path: '/metrics'

  - job_name: 'postgres'
    scrape_interval: 15s
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis'
    scrape_interval: 15s
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
